const EXCHANGE_NAMES: Record<string, string> = {
  NMS: "NASDAQ",
  NGM: "NASDAQ Global Market",
  NASDAQ: "NASDAQ",
  NYQ: "NYSE",
  NYSE: "NYSE",
  XETRA: "Xetra Frankfurt",
  FRA: "Frankfurt",
  ETR: "Xetra Frankfurt",
  LSE: "London Stock Exchange",
  LON: "London Stock Exchange",
  PAR: "Euronext Paris",
  EPA: "Euronext Paris",
  AMS: "Euronext Amsterdam",
  BRU: "Euronext Brussels",
  MIL: "Borsa Italiana",
  BIT: "Borsa Italiana",
  CPH: "Nasdaq Copenhagen",
  STO: "Nasdaq Stockholm",
  HEL: "Nasdaq Helsinki",
  OSL: "Oslo Bors",
  SWX: "SIX Swiss Exchange",
  TSE: "Tokyo Stock Exchange",
  HKG: "Hong Kong Stock Exchange",
  KRX: "Korea Exchange",
  BSE: "Bombay Stock Exchange",
  NSE: "National Stock Exchange India",
  ASX: "Australian Securities Exchange",
  JSE: "Johannesburg Stock Exchange",
  TSX: "Toronto Stock Exchange",
  BMV: "Mexican Stock Exchange",
  BVMF: "B3 Sao Paulo",
  MCX: "Moscow Exchange",
  TADAWUL: "Saudi Stock Exchange",
};

export function getExchangeName(code: string): string {
  return EXCHANGE_NAMES[code] ?? code;
}
