import type {
  StockPick,
  EtfPick,
  Broker,
  PricingTier,
  PassOption,
  FaqItem,
  WatchlistItem,
  Alert,
  BrokerId,
  UserRegion,
} from "./types";

// ── Broker availability shorthand ──

const allBrokers: BrokerId[] = ["ibkr", "t212", "robinhood", "etoro"];
const usAndIbkr: BrokerId[] = ["ibkr", "t212", "robinhood"];
const euBrokers: BrokerId[] = ["ibkr", "t212", "etoro"];
const ibkrOnly: BrokerId[] = ["ibkr"];
const deBrokers: BrokerId[] = ["ibkr", "traderepublic", "scalable", "ing", "comdirect"];
const deAndT212: BrokerId[] = ["ibkr", "t212", "traderepublic", "scalable"];

// ── US broker IDs / DE broker IDs for filtering ──

export const usBrokerIds: BrokerId[] = ["robinhood", "fidelity", "schwab", "ibkr", "webull"];
export const deBrokerIds: BrokerId[] = ["traderepublic", "scalable", "ing", "ibkr", "t212", "comdirect"];
export const globalBrokerIds: BrokerId[] = ["ibkr"];

// ── Stocks ──

export const stockPicks: StockPick[] = [
  {
    symbol: "NVDA",
    name: "NVIDIA Corp.",
    price: 812.4,
    upside: 18,
    target: 960,
    buys: 42,
    holds: 5,
    sells: 1,
    analysts: 48,
    sector: "Semiconductors",
    risk: "high",
    horizon: "12M",
    region: "us",
    exchange: "NASDAQ",
    currency: "USD",
    brokerAvailability: allBrokers,
    dividendYield: 0.03,
    marketCap: "mega",
    description:
      "Leading designer of GPUs for gaming, data centers, and AI workloads.",
    whyThisPick:
      "48 analysts cover NVIDIA with near-unanimous buy consensus (87.5%). The average 12-month target of $960 implies 18% upside from current levels. AI infrastructure spending continues to accelerate, and NVIDIA holds >80% market share in data center GPUs.",
    belowSma200: false,
  },
  {
    symbol: "MSFT",
    name: "Microsoft",
    price: 426.2,
    upside: 11,
    target: 472,
    buys: 34,
    holds: 4,
    sells: 0,
    analysts: 38,
    sector: "Software",
    risk: "low",
    horizon: "12M",
    region: "us",
    exchange: "NASDAQ",
    currency: "USD",
    brokerAvailability: allBrokers,
    dividendYield: 0.72,
    marketCap: "mega",
    description: "Enterprise software giant with Azure cloud and AI integration.",
    whyThisPick:
      "Zero sell ratings from 38 analysts signal exceptional conviction. Azure cloud growth re-accelerated with AI workloads. The Copilot suite is driving incremental revenue across Office 365. Low-risk, steady compounder.",
    belowSma200: false,
  },
  {
    symbol: "AVGO",
    name: "Broadcom",
    price: 1288.1,
    upside: 14,
    target: 1470,
    buys: 29,
    holds: 6,
    sells: 0,
    analysts: 35,
    sector: "Semiconductors",
    risk: "balanced",
    horizon: "12M",
    region: "us",
    exchange: "NASDAQ",
    currency: "USD",
    brokerAvailability: allBrokers,
    dividendYield: 1.24,
    marketCap: "mega",
    description:
      "Diversified semiconductor company with networking, broadband, and enterprise software.",
    whyThisPick:
      "VMware acquisition creates a combined hardware+software platform. Custom AI accelerator business (XPU) growing rapidly with hyperscaler customers. Strong free cash flow funds a growing dividend.",
    belowSma200: false,
  },
  {
    symbol: "LULU",
    name: "Lululemon Athletica",
    price: 426.5,
    upside: 22,
    target: 520,
    buys: 21,
    holds: 8,
    sells: 2,
    analysts: 31,
    sector: "Consumer",
    risk: "balanced",
    horizon: "12M",
    region: "us",
    exchange: "NASDAQ",
    currency: "USD",
    brokerAvailability: usAndIbkr,
    dividendYield: 0,
    marketCap: "large",
    description: "Premium athletic apparel brand with strong DTC presence.",
    whyThisPick:
      "Highest upside in the list at 22%. International expansion (especially China) is an untapped growth lever. Brand loyalty drives repeat purchase rates above 90%. Recent inventory normalization positions the company for margin recovery.",
    belowSma200: false,
  },
  {
    symbol: "SHOP",
    name: "Shopify",
    price: 88.6,
    upside: 19,
    target: 105.4,
    buys: 28,
    holds: 10,
    sells: 3,
    analysts: 41,
    sector: "E-Commerce",
    risk: "high",
    horizon: "12M",
    region: "us",
    exchange: "NYSE",
    currency: "USD",
    brokerAvailability: allBrokers,
    dividendYield: 0,
    marketCap: "large",
    description:
      "E-commerce platform powering online stores and retail POS systems.",
    whyThisPick:
      "Post-logistics divestiture, Shopify is now a lean, high-margin SaaS platform. Merchant solutions revenue growing 25%+ YoY. Checkout extensibility and Shop Pay adoption are deepening the moat. Higher risk due to valuation multiple.",
    belowSma200: false,
  },
  {
    symbol: "MCD",
    name: "McDonald's",
    price: 291.2,
    upside: 9,
    target: 318.0,
    buys: 26,
    holds: 9,
    sells: 0,
    analysts: 35,
    sector: "Consumer",
    risk: "low",
    horizon: "12M",
    region: "us",
    exchange: "NYSE",
    currency: "USD",
    brokerAvailability: allBrokers,
    dividendYield: 2.31,
    marketCap: "mega",
    description: "Global fast-food franchise operator and real estate company.",
    whyThisPick:
      "Zero sell ratings from 35 analysts. McDonald's is a defensive play with a franchise-heavy model generating consistent cash flow. Digital ordering now represents 40%+ of sales in top markets. Modest upside but very high conviction.",
    belowSma200: false,
  },
  {
    symbol: "AMZN",
    name: "Amazon",
    price: 186.4,
    upside: 16,
    target: 216.2,
    buys: 52,
    holds: 3,
    sells: 0,
    analysts: 55,
    sector: "E-Commerce",
    risk: "balanced",
    horizon: "12M",
    region: "us",
    exchange: "NASDAQ",
    currency: "USD",
    brokerAvailability: allBrokers,
    dividendYield: 0,
    marketCap: "mega",
    description:
      "E-commerce, cloud computing (AWS), and digital advertising conglomerate.",
    whyThisPick:
      "Most-covered stock in our universe with 55 analysts and zero sells. AWS margin expansion, advertising revenue growth, and retail efficiency gains create a triple tailwind. Broad diversification across revenue streams reduces single-segment risk.",
    belowSma200: false,
  },
  {
    symbol: "CRWD",
    name: "CrowdStrike",
    price: 312.8,
    upside: 21,
    target: 378.5,
    buys: 38,
    holds: 7,
    sells: 1,
    analysts: 46,
    sector: "Cybersecurity",
    risk: "high",
    horizon: "12M",
    region: "us",
    exchange: "NASDAQ",
    currency: "USD",
    brokerAvailability: allBrokers,
    dividendYield: 0,
    marketCap: "large",
    description: "Cloud-native endpoint security and threat intelligence platform.",
    whyThisPick:
      "21% upside with strong conviction (82% buy). The Falcon platform's module adoption is expanding ARR per customer. Cybersecurity spending is recession-resistant. Post-outage recovery is ahead of expectations.",
    belowSma200: false,
  },
  {
    symbol: "LLY",
    name: "Eli Lilly",
    price: 742.3,
    upside: 15,
    target: 853.6,
    buys: 22,
    holds: 5,
    sells: 1,
    analysts: 28,
    sector: "Healthcare",
    risk: "balanced",
    horizon: "12M",
    region: "us",
    exchange: "NYSE",
    currency: "USD",
    brokerAvailability: allBrokers,
    dividendYield: 0.65,
    marketCap: "mega",
    description: "Pharmaceutical company leading in GLP-1, diabetes, and oncology.",
    whyThisPick:
      "GLP-1 drug Mounjaro/Zepbound is a generational revenue opportunity with $50B+ peak sales potential. Pipeline depth in Alzheimer's and oncology provides additional catalysts. Supply constraints are easing.",
    belowSma200: false,
  },
  {
    symbol: "INTC",
    name: "Intel Corp.",
    price: 31.2,
    upside: 28,
    target: 39.9,
    buys: 8,
    holds: 22,
    sells: 10,
    analysts: 40,
    sector: "Semiconductors",
    risk: "high",
    horizon: "12M",
    region: "us",
    exchange: "NASDAQ",
    currency: "USD",
    brokerAvailability: allBrokers,
    dividendYield: 1.6,
    marketCap: "large",
    description: "Legacy chipmaker undergoing foundry transformation.",
    whyThisPick:
      "High upside (28%) but low conviction — only 20% buy ratings with significant sell pressure. Foundry turnaround is a multi-year bet with uncertain execution. Included as an example of a high-upside, low-conviction pick where our scoring applies a heavy discount.",
    belowSma200: true,
  },
  // European stocks
  {
    symbol: "ASML",
    name: "ASML Holding",
    price: 684.5,
    upside: 20,
    target: 821.4,
    buys: 28,
    holds: 4,
    sells: 0,
    analysts: 32,
    sector: "Semiconductors",
    risk: "balanced",
    horizon: "12M",
    region: "europe",
    exchange: "Euronext Amsterdam",
    currency: "EUR",
    brokerAvailability: euBrokers,
    dividendYield: 0.82,
    marketCap: "mega",
    description: "Monopoly supplier of EUV lithography machines for advanced chip manufacturing.",
    whyThisPick:
      "ASML is the sole supplier of EUV lithography — every leading-edge chip on earth requires their machines. 87% buy ratings. AI-driven demand for advanced nodes is accelerating orders. Not available on Robinhood.",
    belowSma200: false,
  },
  {
    symbol: "NOVO-B",
    name: "Novo Nordisk",
    price: 742.8,
    upside: 17,
    target: 869.1,
    buys: 20,
    holds: 6,
    sells: 2,
    analysts: 28,
    sector: "Healthcare",
    risk: "balanced",
    horizon: "12M",
    region: "europe",
    exchange: "Copenhagen",
    currency: "DKK",
    brokerAvailability: ["ibkr", "t212", "etoro"],
    dividendYield: 1.15,
    marketCap: "mega",
    description: "Global leader in GLP-1 diabetes and obesity treatments (Ozempic, Wegovy).",
    whyThisPick:
      "GLP-1 market leader with Ozempic/Wegovy generating $30B+ in annual revenue. Obesity treatment is a multi-decade secular trend. European listing means not all US brokers carry it — IBKR and Trading 212 do, Robinhood does not.",
    belowSma200: false,
  },
  {
    symbol: "SAP",
    name: "SAP SE",
    price: 218.6,
    upside: 12,
    target: 244.8,
    buys: 22,
    holds: 8,
    sells: 1,
    analysts: 31,
    sector: "Software",
    risk: "low",
    horizon: "12M",
    region: "europe",
    exchange: "XETRA",
    currency: "EUR",
    brokerAvailability: euBrokers,
    dividendYield: 1.05,
    marketCap: "mega",
    description: "Enterprise resource planning (ERP) software leader migrating to cloud.",
    whyThisPick:
      "Cloud transition driving recurring revenue growth of 25%+ YoY. Dominant market position in enterprise ERP with high switching costs. Low risk defensive pick with steady dividend. Listed in Frankfurt — available via IBKR, T212, eToro.",
    belowSma200: false,
  },
  // German blue-chips
  {
    symbol: "SIE",
    name: "Siemens AG",
    price: 192.4,
    upside: 14,
    target: 219.3,
    buys: 18,
    holds: 7,
    sells: 1,
    analysts: 26,
    sector: "Industrials",
    risk: "balanced",
    horizon: "12M",
    region: "europe",
    exchange: "XETRA",
    currency: "EUR",
    brokerAvailability: deBrokers,
    dividendYield: 2.2,
    marketCap: "mega",
    description: "German industrial conglomerate with digital industries, smart infrastructure, and mobility.",
    whyThisPick:
      "Siemens is Europe's largest industrial technology company. Digital Industries and Smart Infrastructure divisions benefit from factory automation and building efficiency megatrends. Strong dividend and defensive positioning.",
    belowSma200: false,
  },
  {
    symbol: "ALV",
    name: "Allianz SE",
    price: 284.6,
    upside: 11,
    target: 315.9,
    buys: 16,
    holds: 6,
    sells: 0,
    analysts: 22,
    sector: "Insurance",
    risk: "low",
    horizon: "12M",
    region: "europe",
    exchange: "XETRA",
    currency: "EUR",
    brokerAvailability: deBrokers,
    dividendYield: 4.1,
    marketCap: "mega",
    description: "Europe's largest insurance and asset management group (PIMCO).",
    whyThisPick:
      "Zero sell ratings from 22 analysts. Allianz combines insurance premium income with asset management (PIMCO). High dividend yield of 4.1% makes it a top income pick for German investors. Low risk, steady compounder.",
    belowSma200: false,
  },
  {
    symbol: "DTE",
    name: "Deutsche Telekom",
    price: 26.8,
    upside: 15,
    target: 30.8,
    buys: 20,
    holds: 4,
    sells: 1,
    analysts: 25,
    sector: "Telecom",
    risk: "low",
    horizon: "12M",
    region: "europe",
    exchange: "XETRA",
    currency: "EUR",
    brokerAvailability: deBrokers,
    dividendYield: 3.4,
    marketCap: "mega",
    description: "Europe's largest telecom, majority owner of T-Mobile US.",
    whyThisPick:
      "T-Mobile US drives the growth story — US mobile market share gains and free cash flow generation. European operations provide stable cash flows. Attractive dividend yield and Sparplan-friendly share price for German retail investors.",
    belowSma200: false,
  },
  {
    symbol: "IFX",
    name: "Infineon Technologies",
    price: 34.2,
    upside: 24,
    target: 42.4,
    buys: 22,
    holds: 5,
    sells: 2,
    analysts: 29,
    sector: "Semiconductors",
    risk: "high",
    horizon: "12M",
    region: "europe",
    exchange: "XETRA",
    currency: "EUR",
    brokerAvailability: deAndT212,
    dividendYield: 0.9,
    marketCap: "large",
    description: "German chipmaker focused on automotive, industrial, and power semiconductors.",
    whyThisPick:
      "EV adoption and industrial automation drive demand for Infineon's power semiconductors. 24% upside with 76% buy consensus. Cyclical exposure adds risk, but secular EV/automation tailwinds support long-term thesis.",
    belowSma200: false,
  },
  {
    symbol: "MUV2",
    name: "Munich Re",
    price: 468.2,
    upside: 10,
    target: 515.0,
    buys: 14,
    holds: 8,
    sells: 1,
    analysts: 23,
    sector: "Insurance",
    risk: "low",
    horizon: "12M",
    region: "europe",
    exchange: "XETRA",
    currency: "EUR",
    brokerAvailability: deBrokers,
    dividendYield: 3.2,
    marketCap: "mega",
    description: "World's largest reinsurer with consistent profitability and shareholder returns.",
    whyThisPick:
      "Munich Re is the global reinsurance leader with pricing power in a hardening market. Consistent dividend growth and share buybacks. Low-risk defensive play with steady 10% upside and 3.2% yield.",
    belowSma200: false,
  },
  {
    symbol: "RHM",
    name: "Rheinmetall",
    price: 582.4,
    upside: 19,
    target: 693.1,
    buys: 12,
    holds: 3,
    sells: 0,
    analysts: 15,
    sector: "Defense",
    risk: "high",
    horizon: "12M",
    region: "europe",
    exchange: "XETRA",
    currency: "EUR",
    brokerAvailability: deAndT212,
    dividendYield: 0.8,
    marketCap: "large",
    description: "Germany's leading defense and automotive supplier, benefiting from NATO rearmament.",
    whyThisPick:
      "European defense spending surge driven by NATO 2% GDP targets and the Zeitenwende. Zero sell ratings. Order backlog growing rapidly. High upside but smaller analyst coverage. ESG-sensitive investors may avoid defense stocks.",
    belowSma200: false,
  },
  // Emerging market stocks
  {
    symbol: "TSM",
    name: "Taiwan Semiconductor",
    price: 168.4,
    upside: 19,
    target: 200.4,
    buys: 32,
    holds: 3,
    sells: 0,
    analysts: 35,
    sector: "Semiconductors",
    risk: "balanced",
    horizon: "12M",
    region: "em",
    exchange: "NYSE (ADR)",
    currency: "USD",
    brokerAvailability: allBrokers,
    dividendYield: 1.42,
    marketCap: "mega",
    description: "World's largest semiconductor foundry, manufacturing chips for Apple, NVIDIA, AMD.",
    whyThisPick:
      "Zero sell ratings. TSMC manufactures the most advanced chips on earth — Apple, NVIDIA, AMD all depend on them. AI chip demand is filling capacity for years ahead. ADR trades on NYSE so available on all brokers.",
    belowSma200: false,
  },
  {
    symbol: "BABA",
    name: "Alibaba Group",
    price: 92.3,
    upside: 32,
    target: 121.8,
    buys: 24,
    holds: 8,
    sells: 4,
    analysts: 36,
    sector: "E-Commerce",
    risk: "high",
    horizon: "12M",
    region: "em",
    exchange: "NYSE (ADR)",
    currency: "USD",
    brokerAvailability: ["ibkr", "t212", "etoro"],
    dividendYield: 1.8,
    marketCap: "large",
    description: "Chinese e-commerce and cloud giant with AI investments.",
    whyThisPick:
      "Highest raw upside at 32%, but conviction is mixed — 67% buy with notable sell pressure. China regulatory risk is the key overhang. Cloud + AI narrative is improving. Not on Robinhood. High risk, high potential reward.",
    belowSma200: false,
  },
  {
    symbol: "MELI",
    name: "MercadoLibre",
    price: 1642.0,
    upside: 16,
    target: 1904.7,
    buys: 18,
    holds: 3,
    sells: 0,
    analysts: 21,
    sector: "E-Commerce",
    risk: "high",
    horizon: "12M",
    region: "em",
    exchange: "NASDAQ",
    currency: "USD",
    brokerAvailability: usAndIbkr,
    dividendYield: 0,
    marketCap: "large",
    description: "Latin America's largest e-commerce and fintech platform.",
    whyThisPick:
      "Zero sell ratings from 21 analysts. Dominant e-commerce + fintech position in LatAm with Mercado Pago. E-commerce penetration in the region still below 15%, leaving long runway. High absolute price limits fractional-only brokers.",
    belowSma200: false,
  },
];

// ── ETFs ──

export const etfPicks: EtfPick[] = [
  {
    symbol: "VTI",
    name: "Vanguard Total Stock Market",
    cagr1y: 14.2,
    cagr3y: 9.8,
    cagr5y: 11.2,
    drawdown: -33,
    fee: 0.03,
    sharpe: 0.78,
    theme: "Core US Market",
    region: "us",
    exchange: "NYSE Arca",
    currency: "USD",
    brokerAvailability: allBrokers,
    description:
      "Tracks the entire US equity market — large, mid, small, and micro cap. The default anchor for any portfolio.",
  },
  {
    symbol: "QQQM",
    name: "Invesco NASDAQ 100",
    cagr1y: 22.1,
    cagr3y: 14.3,
    cagr5y: 16.1,
    drawdown: -35,
    fee: 0.15,
    sharpe: 0.95,
    theme: "Growth / Tech",
    region: "us",
    exchange: "NASDAQ",
    currency: "USD",
    brokerAvailability: allBrokers,
    description:
      "Concentrated exposure to the 100 largest non-financial NASDAQ stocks. Heavy tech/growth tilt.",
  },
  {
    symbol: "SCHD",
    name: "Schwab US Dividend Equity",
    cagr1y: 8.6,
    cagr3y: 7.2,
    cagr5y: 10.4,
    drawdown: -26,
    fee: 0.06,
    sharpe: 0.82,
    theme: "Income / Dividends",
    region: "us",
    exchange: "NYSE Arca",
    currency: "USD",
    brokerAvailability: usAndIbkr,
    description:
      "Focuses on high-quality dividend-paying US stocks. Lower volatility, consistent income stream.",
  },
  {
    symbol: "VXUS",
    name: "Vanguard Total International",
    cagr1y: 5.8,
    cagr3y: 4.1,
    cagr5y: 6.1,
    drawdown: -37,
    fee: 0.07,
    sharpe: 0.55,
    theme: "International",
    region: "global",
    exchange: "NYSE Arca",
    currency: "USD",
    brokerAvailability: allBrokers,
    description:
      "Broad international equity exposure outside the US. Diversifies geographic risk.",
  },
  {
    symbol: "BND",
    name: "Vanguard Total Bond Market",
    cagr1y: 3.2,
    cagr3y: -0.8,
    cagr5y: 1.1,
    drawdown: -18,
    fee: 0.03,
    sharpe: 0.31,
    theme: "Bonds / Stability",
    region: "us",
    exchange: "NYSE Arca",
    currency: "USD",
    brokerAvailability: usAndIbkr,
    description:
      "US investment-grade bond exposure. Provides ballast during equity drawdowns.",
  },
  {
    symbol: "VGT",
    name: "Vanguard Information Technology",
    cagr1y: 25.3,
    cagr3y: 16.8,
    cagr5y: 19.4,
    drawdown: -34,
    fee: 0.1,
    sharpe: 0.92,
    theme: "Technology Sector",
    region: "us",
    exchange: "NYSE Arca",
    currency: "USD",
    brokerAvailability: allBrokers,
    description:
      "Pure technology sector exposure. Higher growth potential with higher concentration risk.",
  },
  {
    symbol: "VWCE",
    name: "Vanguard FTSE All-World (Acc)",
    cagr1y: 12.1,
    cagr3y: 8.4,
    cagr5y: 10.2,
    drawdown: -34,
    fee: 0.22,
    sharpe: 0.72,
    theme: "Core Global Market",
    region: "global",
    exchange: "Euronext Amsterdam",
    currency: "EUR",
    brokerAvailability: euBrokers,
    description:
      "UCITS-compliant all-world equity ETF popular with European investors. Accumulating version reinvests dividends. Not available on Robinhood.",
  },
  {
    symbol: "EIMI",
    name: "iShares Core MSCI EM IMI",
    cagr1y: 4.2,
    cagr3y: 1.8,
    cagr5y: 4.6,
    drawdown: -38,
    fee: 0.18,
    sharpe: 0.42,
    theme: "Emerging Markets",
    region: "em",
    exchange: "London",
    currency: "GBP",
    brokerAvailability: ["ibkr", "t212"],
    description:
      "Broad emerging market exposure across large, mid, and small caps. UCITS-compliant. Only available on IBKR and Trading 212.",
  },
  {
    symbol: "CSPX",
    name: "iShares Core S&P 500 (Acc)",
    cagr1y: 15.8,
    cagr3y: 11.2,
    cagr5y: 12.9,
    drawdown: -33,
    fee: 0.07,
    sharpe: 0.85,
    theme: "Core US Large Cap",
    region: "us",
    exchange: "London",
    currency: "USD",
    brokerAvailability: euBrokers,
    description:
      "UCITS-compliant S&P 500 tracker, accumulating. The European-friendly alternative to VOO/SPY. Listed in London, not available on Robinhood.",
  },
  // German UCITS ETFs
  {
    symbol: "IWDA",
    name: "iShares MSCI World (Acc)",
    cagr1y: 13.4,
    cagr3y: 9.6,
    cagr5y: 11.0,
    drawdown: -34,
    fee: 0.2,
    sharpe: 0.76,
    theme: "Core Global Market",
    region: "global",
    exchange: "XETRA",
    currency: "EUR",
    brokerAvailability: deAndT212,
    description:
      "The most popular UCITS ETF for German Sparplan investors. Tracks MSCI World (developed markets). Accumulating — no dividend tax drag in Germany.",
  },
  {
    symbol: "XDWD",
    name: "Xtrackers MSCI World (Acc)",
    cagr1y: 13.2,
    cagr3y: 9.4,
    cagr5y: 10.8,
    drawdown: -34,
    fee: 0.19,
    sharpe: 0.75,
    theme: "Core Global Market",
    region: "global",
    exchange: "XETRA",
    currency: "EUR",
    brokerAvailability: deAndT212,
    description:
      "DWS/Xtrackers alternative to iShares MSCI World. Slightly lower TER. Popular with Scalable Capital and Trade Republic Sparplan users.",
  },
  {
    symbol: "ISAC",
    name: "iShares MSCI ACWI (Acc)",
    cagr1y: 11.8,
    cagr3y: 8.1,
    cagr5y: 9.6,
    drawdown: -35,
    fee: 0.2,
    sharpe: 0.7,
    theme: "Core Global Market",
    region: "global",
    exchange: "XETRA",
    currency: "EUR",
    brokerAvailability: deAndT212,
    description:
      "All-Country World Index including emerging markets. Single-ETF global portfolio solution. UCITS-compliant, XETRA-listed.",
  },
  {
    symbol: "DBXD",
    name: "Xtrackers DAX (Acc)",
    cagr1y: 16.2,
    cagr3y: 8.8,
    cagr5y: 9.1,
    drawdown: -40,
    fee: 0.09,
    sharpe: 0.62,
    theme: "Germany / DAX",
    region: "europe",
    exchange: "XETRA",
    currency: "EUR",
    brokerAvailability: deBrokers,
    description:
      "Tracks the DAX 40 — Germany's blue-chip index. Low cost at 0.09% TER. Home-bias play for German investors. Concentrated in 40 stocks.",
  },
];

// ── Brokers ──

export const brokers: Broker[] = [
  {
    id: "ibkr",
    name: "Interactive Brokers",
    logo: "IBKR",
    fractional: true,
    commission: "$0 (IBKR Lite)",
    minDeposit: "$0",
    features: [
      "Global market access (150+ markets)",
      "Advanced tools",
      "Fractional shares",
      "Low margin rates",
    ],
    cta: "Open IBKR Account",
    regions: ["us", "de"],
  },
  {
    id: "t212",
    name: "Trading 212",
    logo: "T212",
    fractional: true,
    commission: "$0",
    minDeposit: "$1",
    features: [
      "Commission-free",
      "Fractional shares",
      "Auto-invest pies",
      "EU/UK friendly",
    ],
    cta: "Open Trading 212",
    regions: ["us", "de"],
    sparplan: true,
    sparplanMin: "€1",
  },
  {
    id: "robinhood",
    name: "Robinhood",
    logo: "HOOD",
    fractional: true,
    commission: "$0",
    minDeposit: "$0",
    features: [
      "Commission-free",
      "Fractional shares",
      "Options trading",
      "US stocks only",
    ],
    cta: "Open Robinhood",
    regions: ["us"],
  },
  {
    id: "etoro",
    name: "eToro",
    logo: "ETRO",
    fractional: true,
    commission: "$0 (stocks)",
    minDeposit: "$50",
    features: [
      "Social trading",
      "Copy portfolios",
      "Multi-asset",
      "Global access",
    ],
    cta: "Open eToro Account",
    regions: ["us", "de"],
  },
  // US brokers
  {
    id: "fidelity",
    name: "Fidelity",
    logo: "FID",
    fractional: true,
    commission: "$0",
    minDeposit: "$0",
    features: [
      "Commission-free stocks & ETFs",
      "Fractional shares",
      "Excellent research",
      "No account minimums",
    ],
    cta: "Open Fidelity Account",
    regions: ["us"],
  },
  {
    id: "schwab",
    name: "Charles Schwab",
    logo: "SCHW",
    fractional: true,
    commission: "$0",
    minDeposit: "$0",
    features: [
      "Commission-free trading",
      "Schwab Intelligent Portfolios",
      "Comprehensive research",
      "24/7 customer service",
    ],
    cta: "Open Schwab Account",
    regions: ["us"],
  },
  {
    id: "webull",
    name: "Webull",
    logo: "WBLL",
    fractional: true,
    commission: "$0",
    minDeposit: "$0",
    features: [
      "Commission-free",
      "Extended hours trading",
      "Advanced charting",
      "Paper trading",
    ],
    cta: "Open Webull Account",
    regions: ["us"],
  },
  // German brokers
  {
    id: "traderepublic",
    name: "Trade Republic",
    logo: "TR",
    fractional: true,
    commission: "€1 per trade",
    minDeposit: "€0",
    features: [
      "Sparplan from €1/month",
      "4% interest on cash",
      "8,500+ stocks & ETFs",
      "German BaFin regulated",
    ],
    cta: "Open Trade Republic",
    regions: ["de"],
    sparplan: true,
    sparplanMin: "€1",
  },
  {
    id: "scalable",
    name: "Scalable Capital",
    logo: "SC",
    fractional: true,
    commission: "€0.99 or flat",
    minDeposit: "€0",
    features: [
      "Sparplan from €1/month",
      "PRIME+ flat-rate trading",
      "7,800+ stocks & ETFs",
      "German BaFin regulated",
    ],
    cta: "Open Scalable Capital",
    regions: ["de"],
    sparplan: true,
    sparplanMin: "€1",
  },
  {
    id: "ing",
    name: "ING",
    logo: "ING",
    fractional: false,
    commission: "€4.90 + 0.25%",
    minDeposit: "€0",
    features: [
      "Full-service banking + brokerage",
      "Sparplan from €1/month",
      "Trusted German bank",
      "Wide ETF selection",
    ],
    cta: "Open ING Depot",
    regions: ["de"],
    sparplan: true,
    sparplanMin: "€1",
  },
  {
    id: "comdirect",
    name: "comdirect",
    logo: "CD",
    fractional: false,
    commission: "€3.90 + 0.25%",
    minDeposit: "€0",
    features: [
      "Commerzbank subsidiary",
      "Sparplan from €25/month",
      "Comprehensive research",
      "comdirect community",
    ],
    cta: "Open comdirect Depot",
    regions: ["de"],
    sparplan: true,
    sparplanMin: "€25",
  },
];

// ── Region config ──

export const regionConfigs: Record<
  UserRegion,
  { label: string; currency: string; taxNote?: string }
> = {
  us: {
    label: "United States",
    currency: "USD",
  },
  de: {
    label: "Germany",
    currency: "EUR",
    taxNote:
      "Abgeltungssteuer: 25% + Soli on capital gains above EUR 1,000 Freibetrag (2024+). Accumulating ETFs defer tax until sale.",
  },
};

// ── Pricing ──

export const pricingTiers: PricingTier[] = [
  {
    name: "Free",
    tier: "free",
    price: "$0",
    priceAnnual: "$0",
    description: "Get started with the essentials",
    features: [
      "Top 5 upside stocks (weekly rotation)",
      "1 auto-mix per month",
      "Basic ETF explorer",
      "Broker comparison",
      "Onboarding goal picker",
    ],
    cta: "Get Started",
    highlighted: false,
  },
  {
    name: "Plus",
    tier: "plus",
    price: "$6.99/mo",
    priceAnnual: "$59/yr",
    description: "Full access for active investors",
    features: [
      "Full upside list (refreshed daily)",
      "Unlimited auto-mix + saved mixes",
      "Unlimited watchlists",
      "Price-target alerts",
      "ETF fact sheets & metrics",
      '"Why this pick" detail pages',
      "All filters (sector, risk, region)",
      "Broker comparison",
    ],
    cta: "Start Plus",
    highlighted: true,
  },
];

export const passOptions: PassOption[] = [
  {
    duration: "1day",
    name: "1-Day Pass",
    price: "$2.99",
    priceNumeric: 2.99,
    days: 1,
    description: "1 activation (24 hours of full access)",
    perDay: "$2.99/day",
  },
  {
    duration: "3day",
    name: "3-Day Pass",
    price: "$5.99",
    priceNumeric: 5.99,
    days: 3,
    description: "3 activations (24 hours each, use anytime)",
    perDay: "$2.00/day",
    savings: "Save 33%",
  },
  {
    duration: "12day",
    name: "12-Day Pass",
    price: "$14.99",
    priceNumeric: 14.99,
    days: 12,
    description: "12 activations (24 hours each, use anytime)",
    perDay: "$1.25/day",
    savings: "Best per-day rate",
  },
];

// ── FAQ ──

export const faqItems: FaqItem[] = [
  {
    question: "Is this financial advice?",
    answer:
      "No. Bonistock is an informational tool that aggregates publicly available analyst data. We do not provide personalized investment advice. Always do your own research and consult a licensed financial advisor before making investment decisions.",
  },
  {
    question: "Where does the data come from?",
    answer:
      "We aggregate analyst ratings, price targets, and financial data from commercial data providers with display licenses. All data is delayed (end-of-day). Our scoring engine refreshes nightly.",
  },
  {
    question: "How does the scoring work?",
    answer:
      'Our composite score combines upside potential (gap between current price and average analyst target) with conviction strength (ratio of buy vs sell ratings, weighted by analyst count). We also apply a "trend guardrail" that flags stocks trading below their 200-day moving average.',
  },
  {
    question: "How do you make money?",
    answer:
      "Three ways: (1) Plus subscriptions and pass purchases, (2) affiliate commissions when users open brokerage accounts through our comparison tool, and (3) clearly-labeled sponsored ETF slots. We never sell user data.",
  },
  {
    question: "Can I cancel my subscription anytime?",
    answer:
      "Yes. Cancel anytime from your account settings. You keep access until the end of your billing period. No cancellation fees, no questions asked.",
  },
  {
    question: "What brokers do you support?",
    answer:
      "We show region-appropriate brokers. US users see Robinhood, Fidelity, Charles Schwab, IBKR, and Webull. German users see Trade Republic, Scalable Capital, ING, IBKR, Trading 212, and comdirect. Select your region in Settings.",
  },
];

// ── Mock data for demo ──

export const mockWatchlist: WatchlistItem[] = [
  {
    symbol: "NVDA",
    name: "NVIDIA Corp.",
    price: 812.4,
    change: 12.6,
    changePercent: 1.58,
    upside: 18,
    addedAt: "2026-01-15",
  },
  {
    symbol: "MSFT",
    name: "Microsoft",
    price: 426.2,
    change: -3.1,
    changePercent: -0.72,
    upside: 11,
    addedAt: "2026-01-20",
  },
  {
    symbol: "LULU",
    name: "Lululemon",
    price: 426.5,
    change: 8.4,
    changePercent: 2.01,
    upside: 22,
    addedAt: "2026-02-01",
  },
  {
    symbol: "AMZN",
    name: "Amazon",
    price: 186.4,
    change: 2.1,
    changePercent: 1.14,
    upside: 16,
    addedAt: "2026-02-10",
  },
];

export const mockAlerts: Alert[] = [
  {
    id: "1",
    symbol: "NVDA",
    type: "price_target",
    message: "NVDA reached your target price of $850",
    triggered: true,
    createdAt: "2026-02-15",
  },
  {
    id: "2",
    symbol: "LULU",
    type: "rating_change",
    message: "LULU received 2 new buy ratings this week",
    triggered: true,
    createdAt: "2026-02-14",
  },
  {
    id: "3",
    symbol: "INTC",
    type: "trend_warning",
    message: "INTC is trading below its 200-day moving average",
    triggered: true,
    createdAt: "2026-02-12",
  },
  {
    id: "4",
    symbol: "MSFT",
    type: "price_target",
    message: "Watching MSFT for target price of $470",
    triggered: false,
    createdAt: "2026-02-10",
  },
  {
    id: "5",
    symbol: "SHOP",
    type: "price_target",
    message: "Watching SHOP for target price of $100",
    triggered: false,
    createdAt: "2026-02-08",
  },
];

export const mockUser = {
  username: "admin",
  email: "admin@bonistock.com",
  tier: "plus" as const,
  goal: "growth" as const,
  memberSince: "2026-01-01",
  region: "us" as const,
};
