version: "3.8"

services:
  app:
    image: bonistock:prod
    ports:
      - "3002:3000"
    secrets:
      - bonistock_prod_DATABASE_URL
      - bonistock_prod_NEXTAUTH_SECRET
      - bonistock_prod_STRIPE_SECRET_KEY
      - bonistock_prod_STRIPE_WEBHOOK_SECRET
      - bonistock_prod_STRIPE_PUBLISHABLE_KEY
      - bonistock_prod_BREVO_SMTP_USER
      - bonistock_prod_BREVO_SMTP_KEY
      - bonistock_prod_EMAIL_FROM
      - bonistock_prod_GOOGLE_CLIENT_ID
      - bonistock_prod_GOOGLE_CLIENT_SECRET
      - bonistock_prod_FACEBOOK_CLIENT_ID
      - bonistock_prod_FACEBOOK_CLIENT_SECRET
      - bonistock_prod_FMP_API_KEY
      - bonistock_prod_ENCRYPTION_KEY
      - bonistock_prod_STRIPE_PRICE_PLUS_MONTHLY
      - bonistock_prod_STRIPE_PRICE_PLUS_ANNUAL
      - bonistock_prod_STRIPE_PRICE_PASS_1DAY
      - bonistock_prod_STRIPE_PRICE_PASS_3DAY
      - bonistock_prod_STRIPE_PRICE_PASS_12DAY
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXTAUTH_URL=https://bonistock.com
      - NEXT_PUBLIC_APP_URL=https://bonistock.com
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
      update_config:
        parallelism: 1
        delay: 10s
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

secrets:
  bonistock_prod_DATABASE_URL:
    external: true
  bonistock_prod_NEXTAUTH_SECRET:
    external: true
  bonistock_prod_STRIPE_SECRET_KEY:
    external: true
  bonistock_prod_STRIPE_WEBHOOK_SECRET:
    external: true
  bonistock_prod_STRIPE_PUBLISHABLE_KEY:
    external: true
  bonistock_prod_BREVO_SMTP_USER:
    external: true
  bonistock_prod_BREVO_SMTP_KEY:
    external: true
  bonistock_prod_EMAIL_FROM:
    external: true
  bonistock_prod_GOOGLE_CLIENT_ID:
    external: true
  bonistock_prod_GOOGLE_CLIENT_SECRET:
    external: true
  bonistock_prod_FACEBOOK_CLIENT_ID:
    external: true
  bonistock_prod_FACEBOOK_CLIENT_SECRET:
    external: true
  bonistock_prod_FMP_API_KEY:
    external: true
  bonistock_prod_ENCRYPTION_KEY:
    external: true
  bonistock_prod_STRIPE_PRICE_PLUS_MONTHLY:
    external: true
  bonistock_prod_STRIPE_PRICE_PLUS_ANNUAL:
    external: true
  bonistock_prod_STRIPE_PRICE_PASS_1DAY:
    external: true
  bonistock_prod_STRIPE_PRICE_PASS_3DAY:
    external: true
  bonistock_prod_STRIPE_PRICE_PASS_12DAY:
    external: true
